### ISSUE TITLE
Support IBC denom parsing

### ISSUE THREAD

**Issue by pharr117** [DefiantLabs/cosmos-tax-cli#17]
IBC denominations are stored in the form `ibc/<ibc denom id hash>`, where the hash can be used to identify the information for that specific denom. We should have a parsing method that takes in the IBC denom and returns the actual symbol for that denom.

For example:

ibc/008BFD000A10BCE5F0D4DD819AE1C1EC2942396062DABDD6AE64A655ABC7085B is an IBC token, which will need to be translated to the underlying Symbol. We can attempt to do this with this endpoint:
`/ibc/apps/transfer/v1/denom_traces/{hash} DenomTrace queries a denomination trace information.`

**Comment by jtieri** [comment]
correct, this is what i'm working towards!

**Comment by jtieri** [comment]
I forgot to link this to #399 because at first I wasn't sure if the PR would actually close this issue out.
We should be good now though, we are indexing all of the ibc denom traces with their hash, path and base denom. So while indexing txs if we see an IBC denom, we attempt to query for it in `ibc_denoms` and then we use the base denom to fetch the entry in `denoms`. If there is no entry in `denoms` for this particular base denom then we are adding a new entry to `denoms` where the symbol and human readable name is `unknown`
