### ISSUE TITLE
error="tx message could not be processed. CachedValue is not present.

### ISSUE THREAD

**Issue by danbryan** [DefiantLabs/cosmos-tax-cli#288]
ERR Block 7276817 failed. Reason: {unknown error} error="tx message could not be processed. CachedValue is not present. TX Hash: 642EA287431CCDCCF45A4AC56634E53651245BE395A49DE21475F98722EA438B, Msg type: /osmosis.gamm.poolmodels.stableswap.v1beta1.MsgCreateStableswapPool, Msg index: 0, Code: 11"

**Comment by esaari1** [comment]
Can you share the config file you were using when you got this?

**Comment by danbryan** [comment]
Lets chat tomorrow, and ill show you how to use the docker-compose to replicate these issues.  The only thing you will need to change  should be the block number.

**Comment by KyleMoser** [comment]
@esaari1 FYI, you can go to https://www.mintscan.io/osmosis and search the TX hash (642EA287431CCDCCF45A4AC56634E53651245BE395A49DE21475F98722EA438B) in the top right search field. Then you can see what block the TX is part of, and put it in the config.

**Comment by danbryan** [comment]
@KyleMoser and @esaari1 the block is also in the original comment `7276817`

![image](https://user-images.githubusercontent.com/807940/216210326-ecb9b15e-a029-4f90-b4d5-e6588ab7358d.png)

**Comment by KyleMoser** [comment]
Leaving a comment unless someone else ends up working this instead of me.

Solution to this problem is twofold:

1. Upgrade the lens dependency to use the newest version of Osmosis SDK, then register the stableswap types in lens' ModuleBasics. This will allow the codecs support to make parsing work (e.g. CachedValue errors will go away)
2. Then you will be able to test that the parsers work (e.g. they will work, or at least be easy to fix, if the stableswap pools conform to the same interfaces as the other gamm pools do).

**Comment by pharr117** [comment]
I could be doing this completely wrong, but I believe this one will be a bit more involved than the above.

I tried to update the osmosis package in our `v0.0.7-dl` revision of our lens fork (the one currently imported by cosmos-tax-cli).

For me this breaks, though, because we are replacing the `cosmos-sdk` package in our lens fork with Osmosis' fork of `cosmos-sdk`.

```
replace github.com/cosmos/cosmos-sdk => github.com/osmosis-labs/cosmos-sdk v0.45.1-0.20220611234148-f59c62f19567
```

It seems like their fork is super behind the main `cosmos-sdk` repo:

```
github.com/strangelove-ventures/lens imports
        github.com/strangelove-ventures/lens/cmd imports
        github.com/osmosis-labs/osmosis/v14/x/gamm imports
        github.com/osmosis-labs/osmosis/v14/x/gamm/pool-models/stableswap imports
        github.com/cosmos/cosmos-sdk/x/authz/codec: cannot find module providing package github.com/cosmos/cosmos-sdk/x/authz/codec
```

Again, I could be doing this completely incorrectly, all I did was switch the Osmosis package version to v14 in our lens fork.

**Comment by danbryan** [comment]
I'm not sure this is something we ever fully figured out and came up with a plan for.  I think it was more of a , we need to index osmosis now, and this was the way.  As we grow to support more chains we probably need to think about how we can handle all the different versions of the sdks.  I think we will need to keep a map of chain versions to block-heights and tx types, and react accordingly.  Is something like this doable in lens, or should we consider our own index library as we mature

**Comment by KyleMoser** [comment]
The easiest thing to do is to pick the SDK of the most used chain which is
osmosis. Then for the other chains, if there is a protobuf definition that
doesn't work, import it and put it in a folder in lens.

So yes it is a solved problem.

The only other strategy that would work is to maintain different branches
for each SDK version. Imo that is a dumb strategy and would cause very
major unnecessary headache.

**Comment by danbryan** [comment]
@danbryan will retest indexing

**Comment by danbryan** [comment]
Looks good to me.

cosmos-tax-cli-indexer-1   | 10:27PM INF Indexing Rewards from block: 7276817 to 7276817
cosmos-tax-cli-indexer-1   | 10:27PM INF Hit the last block we're allowed to index, exiting enqueue func.
cosmos-tax-cli-indexer-1   | 10:27PM INF Task ended for DenomUpsertTask
cosmos-tax-cli-indexer-1   | 10:27PM INF Indexing 16 TXs from block 7276817.
cosmos-tax-cli-indexer-1   | 10:27PM INF DB updates complete

**Comment by pharr117** [comment]
Closed by upgrading lens fork version and Osmosis deps
