### ISSUE TITLE
ERR ProcessRpcTxs: unhandled error error="tx message could not be processed. CachedValue is not present. TX Hash: 970C90D362C5FA744CEF2E0429F29BD3D88B2615188EAE04539DA8364CA4D89C, Msg type: /cosmos.authz.v1beta1.MsgExec

### ISSUE THREAD

**Issue by danbryan** [DefiantLabs/cosmos-tax-cli#367]
![image](https://user-images.githubusercontent.com/807940/229156051-32ee9d9b-be4a-4383-bbb3-e7d4b331575f.png)

**Comment by pharr117** [comment]
I have figured this one out and I believe I have a solution.

1. `MsgExec` allows executing arbitrary messages on behalf of an account that has given permission
```
MsgExec
When a grantee wants to execute a transaction on behalf of a granter, they must send MsgExec.
```
2. This particular MsgExec has a `protorev` Msg in the Message array
3. Lens tries to Unpack the Message array values, but was silently failing (see no error checking on [this line](https://github.com/DefiantLabs/lens/blob/1609b0a7b227f71a38eab916c50d75011f8ed5f5/client/query/tx.go#L43)
4. The failure was due to the fact we were not including the new Osmosis `protorev` AppModuleBasic in our Lens fork `ModuleBasics` array, so this TX was failing to be unpacked correctly.

I will implement a fix for it on our Lens fork side, and then push a PR here that uses the fixed Lens version.

**Comment by danbryan** [comment]
@pharr117 thanks, Can you also please tag anything related to protorev with 

labels:
osmosis-1
grants
protorev

I need to show osmosis that we built support for protorev, stableswap, and concentrated liquidty for this grant.  So anything related to them should be labeled.

**Comment by pharr117** [comment]
Will do. The PR I just pushed will not complete the support for `protorev`. We will still need to add TX handlers and rewards handlers for the `protorev` module. But the PR is the first step for it.
