### ISSUE TITLE
Add Cosmos Liquidity Message Types

### ISSUE THREAD

**Issue by danbryan** [DefiantLabs/cosmos-tax-cli#383]
Example of one error.

ERR Error getting transactions by block height (7453602). Err: no concrete type registered for type URL /tendermint.liquidity.v1beta1.MsgDepositWithinBatch against interface *types.Msg.

we should support all these types, they should follow similar logic as the osmosis ones.

https://github.com/tendermint/liquidity/blob/develop/x/liquidity/spec/04_messages.md

- MsgCreatePool
- MsgDepositWithinBatch
- MsgWithdrawWithinBatch
- MsgSwapWithinBatch

**Comment by pharr117** [comment]
In order to support the tendermint liquidity module, we will need to add support for it in 2 places:

1. Our lens fork - we need Lens to be able to be able to handle Unpacking the new message type interfaces from their representation in proto
2. This repo - we need parsers for indexing the message types

I have already begun to look into (1), and its proving somewhat of a heavy lift:

1. The tendermint liquidity module relies on a different version of Cosmos SDK than our Lens fork
2. Trying to just import the tendermint module is not working

I will attempt to just do what we have done for old message types in the past, where we basically only include the required proto definitions and supporting interface definitions and methods to just be able to decode the message.

**Comment by pharr117** [comment]
After doing initial research and a bit of work to allow us to index Tendermint Message types, I have found the following:

1. Tendermint Liquidity messages build up a batch of messages on each pool (thus the batch in the name) - [source](https://github.com/tendermint/liquidity/blob/ce71214b6332c38ec835b8b48f4d0c59055de639/x/liquidity/spec/01_concepts.md#batch-execution)
    * Coins are held in escrow until ready for execution [source](https://github.com/tendermint/liquidity/blob/ce71214b6332c38ec835b8b48f4d0c59055de639/x/liquidity/spec/03_state_transitions.md#coin-escrow-for-liquidity-module-messages)
2. Batches build up over a number of blocks equal to a module Param value of `UnitBatchSize`
3. When the Batch Execution block is hit, all messages in a Batch are executed, and the following happens:
    * If a message is executable - execute it and send funds where they need to go
    * If a message is not executable - refund to wherever the funds need to go
 
The Batch Execution functionality happens in the EndBlocker state transition - [source](https://github.com/tendermint/liquidity/blob/ce71214b6332c38ec835b8b48f4d0c59055de639/x/liquidity/spec/06_end_block.md#execute-liquiditypoolbatch-upon-execution-heights)

To wrap it up, the real work happens in the Block transition state EndBlocker. This is similar to how Osmosis rewards work (except they happen in the BeginBlocker). We will need to index these events, not the messages themselves.

The EndBlocker will contain these event types we need to watch out for [source](https://github.com/tendermint/liquidity/blob/ce71214b6332c38ec835b8b48f4d0c59055de639/x/liquidity/spec/07_events.md#endblocker)

**Comment by pharr117** [comment]
This PR contains methods to handle the above behavior: https://github.com/DefiantLabs/cosmos-tax-cli/pull/391

This PR adds the ability to index Tendermint Liquidity events so we can get the actual data.

I will be pushing another PR later for the following:

1. We need Lens to be able to parse Tendermint Liquidity messages, since it is currently failing to do so with missing Protobuf definitions
2. We will continue to ignore those messages in the Transaction Indexer, since the real work of the Tendermint liquidity module happens in block events.
