### ISSUE TITLE
Noble Integration Info

### ISSUE THREAD

**Issue by danbryan** [DefiantLabs/cosmos-tax-cli#409]
People are interested in having tax reports for `noble-1`. 

In the near future, USDC will be enabled on mainnet enableing frequent micro `uusdc` payments to be paid to the [validators](https://explore.strange.love/noble-1/staking). Most validators  will be required to report this income.

Additionally IBC Atom will be enabled as a global fee for paying for transactions.   

There will soon be 4 assets on noble. 

**Stake** - vested with each val, not liquid.
**IBC Atom** - used to pay fees
**FRNZ** - marketing coin used to redeem real world assets
**USDC** - First generic asset issued on noble.

Questions:

1.) What is our current capability for indexing noble right now? I assume we can handle IBC transfers, Sends, receives, distributions.  You can test with these end points.

Endpoints:
**RPC:** https://rpc.mainnet.noble.strange.love:443
**API:** https://api.mainnet.noble.strange.love:443

2.) Will any custom development need to be done to support the noble specific modules?

- blockibc
- fiattokenfactory - mints tokens
- globalfee - allows ibc atom to be a fee
- tariff - im sure this one is taxable
- tokenfactory

**Comment by pharr117** [comment]
## Question 1
We have basic Cosmos SDK module capabilities for indexing Noble right off the bat. So as you pointed out, we have already developed the capability for what we have determined as having "taxable" implications. Those modules and the messages we support can be found at the Wiki entry here: [Indexer and CSV Parser Support Audit - Cosmos Modules](https://github.com/DefiantLabs/cosmos-tax-cli/wiki/Indexer-and-CSV-Parser-Support-Audit#cosmos-modules)

## Question 2
With the current state of the repo, custom development will for sure need to take place, whether we want to support those module or not. That is for the following reasons:

1. We rely on Lens for our RPC calls to gather Blockchain data. For the queries we use, Lens requires pre-knowledge of which messages it supports in order to cast the messages from proto -> their underlying type
2. When Lens encounters a message it has not seen before, it will throw a type URL error  (see [here](https://github.com/DefiantLabs/cosmos-tax-cli/issues/353) for an example).  This will cause the block to be unparsable in the worst case scenario for our indexer.
3. We will need to include support for Noble custom modules in our Lens repo so that we can get the data for the messages we want to support
4. To support indexing the custom modules, we will then need to do the following:
    * Research and determine which messages we need to index in each module
    * Determine how to pull out the relevant information
    * Develop and test the methods on the blockchain

**Comment by danbryan** [comment]
Noble hinted they are not in a position to pay for a service like this at this time.  I think we should drop this for now unless they re-engage
