### ISSUE TITLE
Commission is being indexed, but not making it to the parser.

### ISSUE THREAD

**Issue by danbryan** [DefiantLabs/cosmos-tax-cli#460]
In this transaction

https://www.mintscan.io/osmosis/transactions/665FA8F1285CAD3434EA976CCDBBB7C529BDF802588E60BE9C0DE039CDD9E593

![image](https://github.com/DefiantLabs/cosmos-indexer/assets/807940/6c457dc0-5fe8-44a9-8e06-d350c23a3299)

The Rewards, and the fees spent to get the rewards are making it to the CSV.

```
deposit,06/26/2023 18:56:58,73.632181,OSMO,,,,,staked,665FA8F1285CAD3434EA976CCDBBB7C529BDF802588E60BE9C0DE039CDD9E593,Address: osmo1dnmz4yzv73lr3lmauuaa0wpwn8zm8s209lezlz 
withdraw,06/26/2023 18:56:58,,,0.009478,OSMO,,,fee,665FA8F1285CAD3434EA976CCDBBB7C529BDF802588E60BE9C0DE039CDD9E593,Address: osmo1dnmz4yzv73lr3lmauuaa0wpwn8zm8s209lezlz 
```

but the commission is not.  However, it does look like we are indexing commissions.  I'm guessing this is a bug in the CSV parser.
https://github.com/DefiantLabs/cosmos-indexer/blob/main/core/tx.go#L47

**Comment by pharr117** [comment]
The root cause of this one is that we seem to have been using a bad event to index these transactions:

See here:

https://github.com/DefiantLabs/cosmos-indexer/blob/85c63f73b0d0a58fee5771f4468ab69f40fa6700/cosmos/modules/distribution/types.go#L75-L82

1. For WithdrawValidatorCommission, we had set out to use the `withdraw_commission` event to grab the amount and receiver
2. We use this event to get the `receiver` key
3. We set the address of the indexed data to this field

The problem is that this event does not have this attribute in this version of the message:

![image](https://github.com/DefiantLabs/cosmos-indexer/assets/24580777/d402ad1a-075d-4747-9a2f-b8d8cf2d896c)

Our code does not throw an error when an attribute is attempted to be grabbed but does not exist, we return an empty string instead which was causing the address to be an empty string.
